#!/usr/bin/env bash

LIBDVDCSS_VERSION=${1:-1.4.3}
HANDBRAKECLI_VERSION=${2:-1.5.1}

docker build --build-arg LIBDVDCSS_VERSION=$LIBDVDCSS_VERSION --build-arg HANDBRAKECLI_VERSION=$HANDBRAKECLI_VERSION --rm -t "multimedia-utils:${LIBDVDCSS_VERSION}-${HANDBRAKECLI_VERSION}" .
