#!/bin/bash

LIBDVDCSS_VERSION=${1:-1.4.2}
HANDBRAKECLI_VERSION=${2:-1.4.0}

docker build --build-arg LIBDVDCSS_VERSION=$LIBDVDCSS_VERSION --build-arg HANDBRAKECLI_VERSION=$HANDBRAKECLI_VERSION --rm -t "multimedia-utils:${LIBDVDCSS_VERSION}-${HANDBRAKECLI_VERSION}" .
